name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11.4
  - seaborn=0.12.2
  - pandas=1.5.3
  - missingno=0.5.2
  - numpy=1.24.3
  - matplotlib=3.7.1
  - xgboost=2.0.2
  - imbalanced-learn=0.11.0
  - umap-learn=0.5.5
  - scikit-learn=1.3.0
  - jupyter=1.0.0
  - make
  - git
